---
    # This Playbook configured Sensu Master
    
    - name: Sensu Install Docker
      hosts: all

      tasks:
        - name: Requirements Pkgs
          package:
            name: 
              - python3-pip
              - python3-setuptools
              - python3-dev
              - build-essential 
              - libssl-dev 
              - libffi-dev
              - python3-wheel
            state: latest

        - name: Pip Pkgs
          pip:
            name:
              - docker-compose
        - name: create directory if they don't exist
          file:
            path: "{{ item }}"
            state: directory
            owner: root
            group: root
            mode: 0777
          loop:
            - /root/agent
            - /root/backend

        - docker_compose:
            project_name: sensu
            state: absent
            definition:
              version: '2'
              services:
                  master:
                    image: chaudric/sensu:5.16.1
                    command: sensu-backend start --etcd-listen-client-urls http://0.0.0.0:2379 --etcd-name {{ansible_hostname}} --etcd-advertise-client-urls http://{{ ansible_default_ipv4.address }}:2379 --etcd-initial-cluster sensu01=http://192.168.2.11:2380,sensu02=http://192.168.2.12:2380,sensu03=http://192.168.2.13:2380 --etcd-initial-cluster-state new --etcd-initial-advertise-peer-urls http://{{ansible_hostname}}:2380 --state-dir /var/sensu/sensu-backend --etcd-listen-peer-urls http://0.0.0.0:2380 --log-level debug --debug
                    hostname: "{{ansible_hostname}}"
                    volumes:
                      - "/root/backend:/var/sensu/sensu-backend"
                    restart: always
                    ports:
                      - "2379:2379"
                      - "2380:2380"
                      - "8080:8080"
                      - "8081:8081"
                      - "6060:6060"
                      - "3000:3000"
                  agent:
                    image: chaudric/sensu:5.16.1
                    command: sensu-agent start --backend-url ws://192.168.2.11:8081,ws://192.168.2.12:8081,ws://192.168.2.13:8081 --subscriptions switches --log-level warn --keepalive-interval 5 --keepalive-timeout 10
                    hostname: "{{ansible_hostname}}"
                    privileged: true
                    pid: host
                    network_mode: host
                    restart: always
                    depends_on:
                      - master
          register: output

        - debug:
            var: output

        - assert:
            that:
            - "master.sensu_master_1.state.running"
            - "agent.sensu_agent_1.state.running"