---
# This Playbook configured resolv.conf using ansble-resolv role

- name: DNS Resolv.conf
  hosts: all
  roles:
    - role: "ahuffman.resolv"
      resolv_nameservers:
        - "8.8.8.8"
        - "8.8.4.4"
      resolv_options:
        - "timeout:2"
        - "rotate"